defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  host: localhost
  username: postgres
  password: postgres
  timeout: 5000
  pool: <%= [ENV.fetch("MAX_THREADS", 5).to_i, ENV.fetch("DB_POOL", 5).to_i].max %>

development:
  database: <%= "rocca" %>_dev
  <<: *defaults

test:
  database: <%= "rocca" %>_test
  <<: *defaults

production: &deploy
  <<: *defaults

staging: *deploy
